//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGC_App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UGC_App.Properties.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemis.
        /// </summary>
        internal static string exploartionsuit {
            get {
                return ResourceManager.GetString("exploartionsuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flug.
        /// </summary>
        internal static string flightsuit {
            get {
                return ResourceManager.GetString("flightsuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        internal static string label_about {
            get {
                return ResourceManager.GetString("label_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Update prüfen.
        /// </summary>
        internal static string label_check_update {
            get {
                return ResourceManager.GetString("label_check_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angedockt.
        /// </summary>
        internal static string label_docket {
            get {
                return ResourceManager.GetString("label_docket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string label_exit {
            get {
                return ResourceManager.GetString("label_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anweisungen.
        /// </summary>
        internal static string label_orders {
            get {
                return ResourceManager.GetString("label_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string label_settings {
            get {
                return ResourceManager.GetString("label_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string label_state {
            get {
                return ResourceManager.GetString("label_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzug.
        /// </summary>
        internal static string label_suit {
            get {
                return ResourceManager.GetString("label_suit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string label_system {
            get {
                return ResourceManager.GetString("label_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Liste.
        /// </summary>
        internal static string label_system_list {
            get {
                return ResourceManager.GetString("label_system_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominator.
        /// </summary>
        internal static string tacticalsuit {
            get {
                return ResourceManager.GetString("tacticalsuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maverick.
        /// </summary>
        internal static string utilitysuit {
            get {
                return ResourceManager.GetString("utilitysuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
